USE [master]
GO
CREATE LOGIN [User_HR] WITH PASSWORD=N'hr123' MUST_CHANGE, DEFAULT_DATABASE=[Northwind], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Northwind]
GO
CREATE USER [User_HR] FOR LOGIN [User_HR]
GO
USE [Northwind]
GO
ALTER ROLE [HRRole] ADD MEMBER [User_HR]
GO
